config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, skip: :all

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'destroy', to: 'devise/sessions#destroy'
  end

  resources :signup ,only: [:index,:create] do
    collection do
      get 'registration'                               
      post 'registration',  to: 'signup#profile_validation' 
      get 'sms_authentication' 
      post 'sms_authentication',  to: 'signup#sms_post'
      get 'sms_confirmation'
      post 'sms_confirmation', to: 'signup#sms_check' 
      get 'address' 
      post 'address', to: 'signup#address_validation' 
      get 'card' 
      get 'done' 
    end
  end  


  resources :users do 
    collection do
      get 'logout'
      get 'profile'
      get 'certification'
      get 'card_registration'
      get 'card_information'
      get 'mypage'
    end
  end

  get 'users/identification(/:id)', to: 'users#identification', as: :user_identification
  resources :items do
    collection do
      get 'category'
    end
    member do
      post 'update_status'
      delete 'destroy_image'
      get 'buy'
      post 'pay'
    end
  end

  get 'items/confirm(/:id)', to: 'items#confirm', as: :items_confirm
  resources :cards


  resources :brands, only: [:index]
  resources :categorys, only: [:index]
end 

  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # extend ActiveHash::Associations::ActiveRecordExtensions
  # belongs_to_active_hash :birthyear
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  
  has_many :sns_credentials
  has_one :address
  has_one :card
  has_one :sale

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
    end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
      )
    end
    return {user: user}
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  PASSWORD_VALIDATION = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,128}+\z/i  

  validates :nickname,                presence: true, length: {maximum: 50}
  validates :email,                   presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password,                presence: true, length: {minimum: 7, maximum: 128},format: { with: PASSWORD_VALIDATION }
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}
  validates :family_name,             presence: true, length: {maximum: 50}
  validates :first_name,              presence: true, length: {maximum: 50}
  validates :family_name_kana,        presence: true, length: {maximum: 50}
  validates :first_name_kana,         presence: true, length: {maximum: 50}
  validates :birthyear,               presence: true, length: {maximum: 50}
  validates :birthmonth,              presence: true, length: {maximum: 50}
  validates :birthday,                presence: true, length: {maximum: 50}
  validates :tel,                     presence: true, length: {maximum: 100},on: :sms_phone

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      render template: "signup/registration" 
    end
  end

  def failure
    redirect_to root_path and return
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  password = Devise.friendly_token.first(7)
  if session[:provider].present? && session[:uid].present?
    @user = User.create(nickname:session[:nickname], email: session[:email], password: "password", password_confirmation: "password", f_name_kana: session[:f_name_kana],l_name_kana: session[:l_name_kana], f_name_kanji: session[:f_name_kanji], l_name_kanji: session[:l_name_kanji], birthday: session[:birthday], tel: params[:user][:tel])
    sns = SnsCredential.create(user_id: @user.id,uid: session[:uid], provider: session[:provider])
  else
    @user = User.create(nickname:session[:nickname], email: session[:email], password: session[:password], password_confirmation: session[:password_confirmation], f_name_kana: session[:f_name_kana],l_name_kana: session[:l_name_kana], f_name_kanji: session[:f_name_kanji], l_name_kanji: session[:l_name_kanji], birthday: session[:birthday], tel: params[:user][:tel])
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def show
    @user = User.find(params[:id])
    @sell_items = Item.where(seller_id: @user.id).order(updated_at: :desc)
  end

  def logout
  end  

  def card_registration
  end
  
  def card_information
  end  

  def certification
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_notification.html.haml
%ul.user-notification
  %li
    .user-notification__logo
      = image_tag("fmarket_smalllogo.png", width: '40')
    .user-notification__body
      .user-notification__body__text
        《まもなく終了！》休暇中に出品して売上金を2倍にしよう！今すぐチェック♪
      .user-notification__body__time
        = icon("far","clock", class: "notification-icon-clock")
        %h3 2日前
      .user-notification__body__arrow
        = icon("fas","angle-right", class: "notification-icon-arrow")
  %li
    .user-notification__logo
      = image_tag("fmarket_smalllogo.png", width: '40')
    .user-notification__body
      .user-notification__body__text
        《1/9まで》「あけおめ」でメルペイをはじめるとP1,000必ずもらえる！さらに抽選で全額ポイント還元のチャンスも！？
      .user-notification__body__time
        = icon("far","clock", class: "notification-icon-clock")
        %h3 3日前
      .user-notification__body__arrow
        = icon("fas","angle-right", class: "notification-icon-arrow")
  %li
    .user-notification__logo
      = image_tag("fmarket_smalllogo.png", width: '40')
    .user-notification__body
      .user-notification__body__text
        《今すぐ参加！》ボタンを押すだけでお年玉が"必ず"もらえるのは今日まで！
      .user-notification__body__time
        = icon("far","clock", class: "notification-icon-clock")
        %h3 4日前
      .user-notification__body__arrow
        = icon("fas","angle-right", class: "notification-icon-arrow")
  %li
    .user-notification__logo
      = image_tag("fmarket_smalllogo.png", width: '40')
    .user-notification__body
      .user-notification__body__text
        事務局から個別メッセージ「《本日終了》今ならポイント倍増！「あけおめ」を入力してメルペイ登録すると合計P2,000もらえる！」
      .user-notification__body__time
        = icon("far","clock", class: "notification-icon-clock")
        %h3 5日前
      .user-notification__body__arrow
        = icon("fas","angle-right", class: "notification-icon-arrow")
  %li
    .user-notification__logo
      = image_tag("fmarket_smalllogo.png", width: '40')
    .user-notification__body
      .user-notification__body__text
        【1月31日まで】最大3%還元！メルペイスマート払いでメルカリのお買い物をしよう！
      .user-notification__body__time
        = icon("far","clock", class: "notification-icon-clock")
        %h3 6日前
      .user-notification__body__arrow
        = icon("fas","angle-right", class: "notification-icon-arrow")

app/views/users/card_information.html.haml
= render partial: "layouts/header"

.content_info
  .content_info__first
    ="メルカリ"
  .content_info__second
    = " 〉"
  .content_info__third
    ="マイページ"
  .content_info__foreth
    = " 〉"
  .content_info__fifth
    = "支払い方法"    
  .content_info__sixth
    = " 〉"
  .content_info__seventh
    = "クレジットカード情報入力"  
      
.container
  .container__side
  = render "shared/side_bar"
 
.container__card_information
  .container__card_information__upper
    %label.main__form__group__label クレジットカード情報入力
  -# .container__card_registration__middle

  -#   .container__card_registration__middle__name
  -#     %label.main__form__group__label クレジットカード一覧
  -#   .container__card_registration__middle__box
  -#     = link_to card_information_users_path, method: :get do
  -#       .container__card_registration__middle__box__card-registration-btn
  -#         .container__card_registration__middle__box__card-registration-btn__image 
  -#           = image_tag 'icons8-credit.png'
  -#         .container__card_registration__middle__box__card-registration-btn__text
  -#           = "クレジットカードを追加する"  
  -# .container__card_registration__lower
  -#   %p.container__card_registration__lower__personal-info
  -#     = link_to root_path, class: 'link', target: '_blank' do
  -#       = '支払方法について'
  -#       %i.fas.fa-chevron-right

app/views/users/card_registration.html.haml
= render partial: "layouts/header"

.content_info
  .content_info__first
    ="メルカリ"
  .content_info__second
    = " 〉"
  .content_info__third
    ="マイページ"
  .content_info__foreth
    = " 〉"
  .content_info__fifth
    = "支払い方法"    
 
.container
  .container__side
  = render "shared/side_bar"
 
.container__card_registration
  .container__card_registration__upper
    %label.main__form__group__label 支払い方法
  .container__card_registration__middle
    .container__card_registration__middle__name
      %label.main__form__group__label クレジットカード一覧
    .container__card_registration__middle__box
      = link_to card_information_users_path, method: :get do
        .container__card_registration__middle__box__card-registration-btn
          .container__card_registration__middle__box__card-registration-btn__image 
            = image_tag 'icons8-credit.png'
          .container__card_registration__middle__box__card-registration-btn__text
            = "クレジットカードを追加する"  
  .container__card_registration__lower
    %p.container__card_registration__lower__personal-info
      = link_to root_path, class: 'link', target: '_blank' do
        = '支払方法について'
        %i.fas.fa-chevron-right

app/views/users/certification.html.haml
= render partial: "layouts/header"

.content_info
  .content_info__first
    ="メルカリ"
  .content_info__second
    = " 〉"
  .content_info__third
    ="マイページ"
  .content_info__foreth
    = " 〉"
  .content_info__fifth
    = "本人情報の登録"    
 
.container
  .container__side
  = render "shared/side_bar"
 
  .container__user_registration
    .container__user_registration__upper
      %label.main__form__group__label 本人情報の登録
    .container__user_registration__lower
      .container__user_registration__lower__comment  
        ="お客さまの本人情報をご登録ください。"
        %br
        ="登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。"
      .container__user_registration__lower__upload
        %p.container__user_registration__lower__upload-info
          = link_to root_path, class: 'container__user_registration__lower__upload', target: '_blank' do
            = '本人確認書類のアップロードについて'
            %i.fas.fa-chevron-right
      .container__user_registration__lower__name    
        %label.container__user_registration__lower__label お名前
        .container__user_registration__lower__name_box
          = "#{current_user.family_name} #{current_user.first_name}"

      .container__user_registration__lower__name_kana    
        %label.container__user_registration__lower__label お名前カナ
        .container__user_registration__lower__name_kana_box
          = "#{current_user.family_name_kana} #{current_user.first_name_kana}"

      .container__user_registration__lower__birthday    
        %label.container__user_registration__lower__label 生年月日
        .container__user_registration__lower__birthday_box
          = "#{current_user.birthyear}/#{current_user.birthmonth}/#{current_user.birthday}"

      .container__user_registration__lower__postal_code    
        %label.container__user_registration__lower__label 郵便番号
        %span.container__user_registration__lower__optional 任意
        %input.container__user_registration__lower__postal_code__box{:placeholder => "#{current_user.address.postal_code}"}/

      .container__user_registration__lower__prefectures   
        %label.container__user_registration__lower__label 都道府県
        %span.container__user_registration__lower__optional 任意
        .container__user_registration__lower__prefectures__select
          = collection_select :address,:prefecture_id,Prefecture.all,:name, :name,{prompt: "#{current_user.address.prefectures}"},{class: "container__user_registration__lower__prefectures__select"}
      .container__user_registration__lower__city   
        %label.container__user_registration__lower__label 市区町村
        %span.container__user_registration__lower__optional 任意
        %input.container__user_registration__lower__city__box{:placeholder => "#{current_user.address.city}"}/        

      .container__user_registration__lower__address    
        %label.container__user_registration__lower__label 番地
        %span.container__user_registration__lower__optional 任意
        %input.container__user_registration__lower__address__box{:placeholder => "#{current_user.address.house_number}"}/              

      .container__user_registration__lower__building    
        %label.container__user_registration__lower__label 建物名
        %span.container__user_registration__lower__optional 任意
        %input.container__user_registration__lower__building__box{:placeholder => "#{current_user.address.building}"}/  

      .container__user_registration__lower__box   
        .container__user_registration__lower__box__user-registration-btn         
          .container__user_registration__lower__box__user-registration-btn__text
            = "登録する"  
      .container__user_registration__lower__registration-info
        %p.container__user_registration__lower__registratiomn-info
          = link_to root_path, class:"container__user_registration__lower__registration-info" , target: '_blank' do
            = '本人情報の登録について'
            %i.fas.fa-chevron-right

app/views/users/index.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 会員情報入力 - メルカリ スマホでかんたん フリマアプリ
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .sign-up
      .header
        = link_to '/' do
          = image_tag 'fmarket_logo_red.svg', alt: 'mercari', class: 'header__logo'
      .main
        .main__text
          新規会員登録
        .main__login
          .main__login__mail
            = link_to new_user_registration_path do
              .main__login__mail--btn
                = icon 'far', 'envelope'
                = "メールアドレスで登録する"
          .main__login__facebook
            = link_to user_facebook_omniauth_authorize_path, method: :post do
              .main__login__facebook--btn
                = icon 'fab', 'facebook-square'
                = "Facebookで登録する"
          .main__login__google
            = link_to user_google_oauth2_omniauth_authorize_path, method: :post do
              .main__login__google--btn
                = "Googleで登録する"
                = icon 'fab', 'google'
      .footer
        %nav
          %ul.clearfix
            %li
              = link_to '#' do
                プライバシーポリシー
            %li
              = link_to '#' do
                メルカリ利用規約
            %li
              = link_to '#' do
                特定商取引に関する表記
        .fotter__logo
          = image_tag 'logo_gray.svg', alt: 'mercari', class: 'footer__logo--gray'
        %p.footer__text
          ©️ 2019 Fmarket

app/views/users/logout.html.haml
= render partial: "layouts/header"

.content_info
  .content_info__first
    ="メルカリ"
  .content_info__second
    = " 〉"
  .content_info__third
    ="マイページ"
  .content_info__foreth
    = " 〉"
  .content_info__fifth
    = "ログアウト"    

.container
  .container__side
    = render "shared/side_bar"
  .container__logout
    = link_to destroy_user_session_path, method: :delete do
      .logout-btn
        = "ログアウト"
    -# %input{type: "submit",value: "ログアウト", current_user_destroy_path, method: :delete ,class: "logout-btn"

app/views/users/mypage.html.haml
= render "layouts/header"

.content_info
  .content_info__first
    ="メルカリ"
  .content_info__second
    = " 〉"
  .content_info__third
    ="マイページ"
- if flash[:del]
  .flash-message.time-limit
    = flash[:del]
.container
  .container__side
    = render "shared/side_bar"
  .container__mypage
    .container__mypage__user
      .container__mypage__user__icon
        = icon("fas","user-circle", class: "user-circle-icon")
      .container__mypage__user__name
        = current_user.nickname
      .container__mypage__user__number
        .container__mypage__user__number__evaluate
          %p 評価 10
        .container__mypage__user__number__exhibit
          %p 出品数 10
    .container__mypage__notification-todo
      %ul.mypage-tabs
        %li.notification
          %h2 お知らせ
        %li.todo
          %h2 やることリスト
      .container__mypage__notification-todo__content
        = render "notification"
        .user-notification-submit
          %button 一覧を見る
        %ul#user-todo
    .container__mypage__buy-item
      %h2.mypage-head 購入した商品
      .container__mypage__notification-todo
        %ul.mypage-tabs
          %li.notification
            %h2 取引中
          %li.todo
            %h2 過去の取引
      .container__mypage__buy-item__content
        %h2 取引中の商品がありません

app/views/users/profile.html.haml
= render "layouts/header"

.content_info
  .content_info__first
    ="メルカリ"
  .content_info__second
    = " 〉"
  .content_info__third
    ="マイページ"
  .content_info__foreth
    = " 〉"
  .content_info__fifth
    = "プロフィール"    

.container
  .container__side
    = render "shared/side_bar"
  .container__main
    %h2 プロフィール
    .container__main__setting
      .container__main__setting__icon
        = icon("fas","user-circle", class: "user-circle-icon")
      .container__main__setting__input
        %input{name: "keyword", placeholder: "例)AYA☆セール中", type: "text", value: "", class: "profile-input"}
    .container__main__content
      %textarea{name: "keyword", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", type: "text", value: "", class: "profile-textarea"}
      %input{type: "submit", value: "変更する", class: "profile-btn"}

app/views/users/show.html.haml
%h1 #{@user.nickname}

%h2 出品商品一覧
.sell-item-index
  - @sell_items.each do |sell_item|
    .sell-item-index__item
      .sell-item-index__item_image
        = image_tag sell_item.item_images[0].image.url, height: '100'
      .sell-item-index__item_name
        = link_to sell_item.name, item_path(sell_item)
      .sell-item-index__item_price
        ¥#{sell_item.price}
      .sell-item-index__item__div
        %p ------------------------------------