config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, skip: :all

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'destroy', to: 'devise/sessions#destroy'
  end

  resources :signup ,only: [:index,:create] do
    collection do
      get 'registration'                               
      post 'registration',  to: 'signup#profile_validation' 
      get 'sms_authentication' 
      post 'sms_authentication',  to: 'signup#sms_post'
      get 'sms_confirmation'
      post 'sms_confirmation', to: 'signup#sms_check' 
      get 'address' 
      post 'address', to: 'signup#address_validation' 
      get 'card' 
      get 'done' 
    end
  end  


  resources :users do 
    collection do
      get 'logout'
      get 'profile'
      get 'certification'
      get 'card_registration'
      get 'card_information'
      get 'mypage'
    end
  end

  get 'users/identification(/:id)', to: 'users#identification', as: :user_identification
  resources :items do
    collection do
      get 'category'
    end
    member do
      post 'update_status'
      delete 'destroy_image'
      get 'buy'
      post 'pay'
    end
  end

  get 'items/confirm(/:id)', to: 'items#confirm', as: :items_confirm
  resources :cards


  resources :brands, only: [:index]
  resources :categorys, only: [:index]
end 

  

app/views/shared/_side_bar.html.haml
.mypage-nav
  .mypage-nav
    .mypage-nav__box
      = link_to mypage_users_path, class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "マイページ"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "お知らせ"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "やることリスト"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "いいね！一覧"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to new_item_path, class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "出品する"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "出品した商品 - 出品中"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right') 
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "出品した商品 - 取引中"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "出品した商品 - 売却済み"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right') 
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "購入した商品 - 取引中"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "購入した商品 - 過去の取引"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')          
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "ニュース一覧"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "評価一覧"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')   
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "ガイド"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')   
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "お問い合わせ"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')             
  .mypage-nav
    .mypage-nav__head
      メルペイ
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "売上・振込申請"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "ポイント"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')           

  .mypage-nav
    .mypage-nav__head
      設定
  .mypage-nav
    .mypage-nav__box
      = link_to profile_users_path, class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "プロフィール"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')                             
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "発送元・お届け先住所変更"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')         
  .mypage-nav
    .mypage-nav__box
      = link_to card_registration_users_path, class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "支払い方法"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right') 
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "メール/パスワード"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right') 
  .mypage-nav
    .mypage-nav__box
      = link_to certification_users_path, class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "本人確認"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right') 
  .mypage-nav
    .mypage-nav__box
      = link_to "#", class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "電話番号の確認"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right') 
  .mypage-nav
    .mypage-nav__box
      = link_to logout_users_path, class: "mypage-nav__box" do
        .mypage-nav__box__item
          = "ログアウト"
        .mypage-nav__box__logo 
          = icon('fas', 'angle-right')            