config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, skip: :all

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'destroy', to: 'devise/sessions#destroy'
  end

  resources :signup ,only: [:index,:create] do
    collection do
      get 'registration'                               
      post 'registration',  to: 'signup#profile_validation' 
      get 'sms_authentication' 
      post 'sms_authentication',  to: 'signup#sms_post'
      get 'sms_confirmation'
      post 'sms_confirmation', to: 'signup#sms_check' 
      get 'address' 
      post 'address', to: 'signup#address_validation' 
      get 'card' 
      get 'done' 
    end
  end  


  resources :users do 
    collection do
      get 'logout'
      get 'profile'
      get 'certification'
      get 'card_registration'
      get 'card_information'
      get 'mypage'
    end
  end

  get 'users/identification(/:id)', to: 'users#identification', as: :user_identification
  resources :items do
    collection do
      get 'category'
    end
    member do
      post 'update_status'
      delete 'destroy_image'
      get 'buy'
      post 'pay'
    end
  end

  get 'items/confirm(/:id)', to: 'items#confirm', as: :items_confirm
  resources :cards


  resources :brands, only: [:index]
  resources :categorys, only: [:index]
end 

  

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :comment, :condition, :size, :price, :arrival_date, :charge, :location, :delivery, :status, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 300 }
  validate :check_category
  belongs_to :buyer, class_name: 'User', optional: true
  belongs_to :seller, class_name: 'User'
  has_many :item_images, dependent: :destroy
  belongs_to :category

  def check_category
    unless category.present? && category.has_grand_parent?
      errors.add(:category, "を選択してください")
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # 本番環境でしか使用しないのでコメントアウト
  # コメントアウトを外せばローカルで使用可能
  # require 'payjp'
  # Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_ACCESS_KEY]
  # before_action :set_item, only: [:show, :destroy, :edit, :update, :update_status, :buy, :pay]
  # before_action :move_to_sign_in, only: [:buy]
  # before_action :item_sold_out?, only: [:buy]
  
  def index
    @items = Item.limit(10)
    
  end
  
  def new
    @item = Item.new
    set_selections(@item)
  end

  def create
    @item = Item.new(item_params)
    @item.status = "出品中"
    if @item.valid? && item_has_1_to_10_images?(@item)
      @item.save
      item_images[:item_images].each do |image|
        @item_image = ItemImage.create(image: image, item_id: @item.id)
      end
      redirect_to item_path @item
    else
      set_selections(@item)
      render :new
    end
  end

  def show
    @seller_items = Item.where.not(id: @item.id).where(seller_id: @item.seller_id).order(updated_at: :desc).limit(6)
    @category_items = Item.where.not(id: @item.id).where(category_id: @item.category_id).order(updated_at: :desc).limit(6)
  end

  def category
    @category = Category.find(params[:id])
    @categorys = @category.children
    respond_to do |format|
      format.json
    end
  end

  def destroy
    if current_user.id == @item.seller_id && @item.destroy
       flash[:del] = "商品を削除しました"
       redirect_to mypage_users_path 
    else
      redirect_to item_path @item
    end
  end

  def edit
    if current_user.id == @item.seller_id 
      set_selections(@item)
    else
      redirect_to action: 'show'
    end
  end

  def update
    if @item.update(item_params) && item_has_1_to_10_images?(@item)
      if item_images[:item_images] != nil
        item_images[:item_images].each do |image|
          @item_image = ItemImage.create(image: image, item_id: @item.id)
        end
      end
      redirect_to item_path @item
    else
      set_selections(@item)
      render :edit
    end
  end

  def update_status
    if @item.status == "出品中"
      @item.status = "公開停止中"
    else @item.status == "公開停止中"
      @item.status = "出品中"
    end
    @item.save if current_user.id == @item.seller_id
    redirect_to item_path @item
  end

  def destroy_image
    @image = ItemImage.find(params[:id])
    @item = Item.find(@image.item_id)
    @image.destroy if current_user.id == @item.seller_id
    set_selections(@item)
    render :edit
  end

  def buy

  end

  def pay
    if @item.status == "出品中"
      @item.status = "売却済み"
      sale = Sale.find(@item.seller.sale.id)
      sale.sales += @item.price
      if @item.valid? && sale.valid? && current_user.card.token.present? && @item.seller_id != current_user.id
        @item.save
        sale.save
        # # 本番環境でしか使用しないのでコメントアウト
        # # コメントアウトを外せばローカルで使用可能
        # payjp_charge(@item, current_user)
        # redirect_to root_path
      else
        render :buy
      end
    else
      render :buy
    end
    
  end


  private
  def item_params
    params.require(:item).permit(:name, :comment, :category_id, :condition, :brand, :size, :price, :arrival_date, :charge, :location, :delivery).merge(seller_id: current_user.id)
  end

  def item_images
    params.require(:item).permit({item_images: []})
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_selections(item)
    if item.category.present?
      if item.category.has_grand_parent?
        @small_categorys = item.category.siblings
        @middle_categorys = item.category.parent.siblings
      elsif item.category.has_parent?
        @middle_categorys = item.category.siblings
      end
    end
    @categorys = Category.where(ancestry: nil)
    @prefectures = Prefecture.all
  end

  def item_has_1_to_10_images?(item)
    result = false
    if item_images[:item_images].present?
      if item.item_images.present?
        result = true if item_images[:item_images].length + item.item_images.length <= 10
      else
        result = true if item_images[:item_images].length <= 10
      end
    else
      result = true if item.item_images.present?
    end
    return result
  end

  # # 本番環境でしか使用しないのでコメントアウト
  # # コメントアウトを外せばローカルで使用可能
  # def payjp_charge(item, user)
  #   charge = Payjp::Charge.create(
  #     amount: item.price,
  #     customer: user.card.token,
  #     currency: 'jpy'
  #   )
  # end

  def move_to_sign_in
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def item_sold_out?
    item = Item.find(params[:id])
    redirect_to item_path @item if item.status == "売却済み"
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_detail.html.haml
.imagebody__flame__itemslists__block
  .imagebody__flame__itemslists__block__image
    =link_to "/items/#{item.id}",class: "imagebody__flame__itemslists__block__image" do 
      = image_tag item.item_images[0].image.url, class: "top-image"
      .top-price
        ¥
        = item.price
      %rinktextcolor.top-name
        = item.name

app/views/items/_form.html.haml
.single-container
  .single-header
    = link_to image_tag("fmarket_logo_red.svg", class: "fmarket-logo")
    
  .single-main
    .single-main__buy-item-container
      .sell-container
        .sell-container__inner
          %h2 商品の情報を入力
          .sell-form
            = form_for item do |f|
              .sell-form__upload
                .sell-form__upload__title
                  %h3 出品画像
                  %h6 必須
                .sell-form__upload__comment
                  %p 最大10枚までアップロードできます
                .sell-form__upload__thumbnails
                  - if item.item_images.length != 0
                    - item.item_images.each do |image|
                      .sell-form__upload__thumbnails__thumbnail
                        .sell-form__upload__thumbnails__thumbnail__image
                          = image_tag image.image.url
                        .sell-form__upload__thumbnails__thumbnail__btn
                          = link_to "削除", destroy_image_item_path(image), method: :delete, remote: true , class: "sell-form__upload__thumbnails__thumbnail__btn__delete"
                = f.label :item_images, class: "sell-form__upload__label" do
                  .sell-form__upload__label__files
                    %p クリックしてファイルをアップロード
                    = f.file_field :item_images, multiple: true
              .sell-form__content
                .sell-form__content__name
                  %label 商品名
                  %h6 必須
                .sell-form__content__input
                  = f.text_field :name, placeholder: "商品名  (必須 40文字まで)", class: "input-default"
                .sell-form__content__explain
                  %label 商品の説明
                  %h6 必須
                .sell-form__content__textarea
                  = f.text_area :comment, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "textarea-default"
              .sell-form__detail
                .sell-form__detail__section
                  %h3 商品の詳細
                .sell-form__detail__selection
                  .sell-form__detail__selection__category
                    %label カテゴリー
                    %h6 必須
                  .sell-form__detail__selection__select
                    .categorys
                      #large-category.categorys-select
                        = f.select :category_id, options_for_select(categorys.map{|c|[c[:name], c[:id]]}), prompt: "---"
                      #middle-category.categorys-select
                        - if middle_categorys != nil
                          = f.select :category_id, options_for_select(middle_categorys.map{|c|[c[:name], c[:id]]}), prompt: "---"
                      #small-category.categorys-select
                        - if small_categorys != nil
                          = f.select :category_id, options_for_select(small_categorys.map{|c|[c[:name], c[:id]]}), prompt: "---"
                  .sell-form__detail__selection__category
                    %label サイズ
                    %h6 必須
                  .sell-form__detail__selection__select
                    = f.select :size, ["S", "M", "L"], prompt: "---"
                  .sell-form__detail__selection__category
                    %label ブランド
                    %h6 任意
                  .sell-form__detail__selection__input
                    = f.text_field :brand, placeholder: "例）シャネル"
                  .sell-form__detail__selection__status
                    %label 商品の状態
                    %h6 必須
                  .sell-form__detail__selection__select
                    = f.select :condition, ["新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"], prompt: "---"
              .sell-form__detail
                .sell-form__detail__section
                  %h3 配送について
                .sell-form__detail__selection
                  .sell-form__detail__selection__category
                    %label 配送料の負担
                    %h6 必須
                  .sell-form__detail__selection__select
                    = f.select :charge, ["送料込み(出品者負担)", "着払い(購入者負担)"], prompt: "---"
                  .sell-form__detail__selection__category
                    %label 配送の方法
                    %h6 必須
                  .sell-form__detail__selection__select
                    = f.select :delivery, ["未定", "らくらくメルカリ便", "ゆうメール"], prompt: "---"
                  .sell-form__detail__selection__status
                    %label 発送元の地域
                    %h6 必須
                  .sell-form__detail__selection__select
                    = f.select :location, options_for_select(prefectures.map{|c|[c[:name], c[:name]]}), prompt: "---"
                  .sell-form__detail__selection__status
                    %label 発送までの日数
                    %h6 必須
                  .sell-form__detail__selection__select
                    = f.select :arrival_date, ["1~2日で発送", "2~3日で発送", "4~7日で発送"], prompt: "---"
              .sell-form__price
                .sell-form__price__price
                  %h3 販売価格(300〜9,999,999)
                .sell-form__price__group
                  .sell-form__price__group__one
                    .sell-form__price__group__one__left
                      %label 価格
                      %h6 必須
                    .sell-form__price__group__one__right
                      ¥
                      #price-input
                        = f.text_field :price, placeholder: "例）300"
                  .sell-form__price__group__two
                    .price-title
                      %p 販売手数料(10%)
                    .price-amount
                      %p#tax -
                  .sell-form__price__group__three
                    .price-title
                      %p 販売利益
                    .price-amount
                      %p#profit -
              .sell-form__btn-box
                %p 禁止されている出品、行為を必ずご確認下さい。
                %p またブランド品でシリアルナンバー等がある場合はご記載下さい。偽ブランドの販売は犯罪であり処罰される可能性があります。
                %p また、出品をもちまして加盟店規約に同意したことになります。
                = f.submit "登録する", class: "submit-btn"
                = link_to "もどる", :back, class: "return-btn"

app/views/items/buy.html.haml
%header
  %h1.PIheader
    = image_tag("fmarket_logo_red.svg", width: '160')
%main.PImain
  %section.PImain__l-single-container
    %h2.PImain__l-single-container__l-single-head.PImain__l-single-container__buy-head
      購入内容の確認
    %section.PImain__l-single-container__buy-content.PImain__l-single-container__buy-item
      .PImain__l-single-container__buy-content-inner
        .PImain__l-single-container__buy-item-box
          %h3.PImain__l-single-container__buy-item-image
            = image_tag @item.item_images[0].image.url, height: "100", width: "100"
          .PImain__l-single-container__buy-item-detail
            %p.PImain__l-single-container__buy-item-name
              #{@item.name}
            %p.PImain__l-single-container__buy-price-ja
              %span
                ¥#{@item.price}
              %span
                （税込）
                - if @item.charge == "送料込み(出品者負担)"
                  送料込み
                - else
                  送料別
    %section.PImain__l-single-container__buy-content.PImain__l-single-container__buy-item
      .PImain__l-single-container__buy-content-inner
        %form.action
          %ul.PImain__l-single-container__buy-price-table
            %lu.PImain__l-single-container__buy-you-pay
              .PImain__l-single-container__buy-price-cell-label
                支払い金額
              .PImain__l-single-container__buy-price-cell
                %span.PImain__l-single-container__buy-you-pay
                  ¥#{@item.price}
          %ul.PImain__l-single-container__buy-accordion
            %lu.PImain__l-single-container__buy-use-point
              ポイントを使用 (所持ポイント: P0)
          %section.PImain__l-single-container__buy-user-info
            .PImain__l-single-container__buy-content-inner
              %h3 支払い方法
              %p クレジットカード
              %p #{current_user.card.number}
              %p 有効期限 #{current_user.card.expiration_month}/#{current_user.card.expiration_year}
          %section.PImain__l-single-container__buy-user-info
            .PImain__l-single-container__buy-content-inner
              %h3 配送先
              %p 〒#{current_user.address.postal_code}
              %p #{current_user.address.prefectures}#{current_user.address.city}#{current_user.address.house_number}#{current_user.address.building}
              %p #{current_user.family_name} #{current_user.first_name}
          %section.PImain__l-single-container__buy-user-info
            .PImain__l-single-container__buy-content-inner
              %p.PImain__l-single-container__buy-form.PImain__l-single-container__has-error-text
              = link_to "購入する", pay_item_path(@item), method: :pots, class: "PImain__l-single-container__btn-default"
              %p.PImain__l-single-container__buy-form.PImain__l-single-container__not-have-app-text
                アプリをお持ちでない方は以下よりインストールしてご利用いただけます。
              .PImain__l-single-container__buy-store-logos
                = link_to image_tag("apple-pay.svg", width: '80'), class:'PImain__l-single-container__rightspacer24'
                = link_to image_tag("google-pay.svg", width: '80')
%footer.PIfooter
  %nav
    %ul.clearfix
      %lu
        プライバシーポリシー
      %lu.spacer
        メルカリ利用規約
      %lu.spacer
        特定商取引に関する表記
  .PIfooter-logo 
    = link_to image_tag("logo_gray.svg", width: '80')
  %p
    %small
      © Mercari, Inc.

app/views/items/edit.html.haml
= render "form", item: @item, categorys: @categorys, middle_categorys: @middle_categorys, small_categorys: @small_categorys, prefectures: @prefectures

app/views/items/index.html.haml
= render partial: "layouts/header"

.applicationintroduction
  .applicationintroduction__image
    = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?2749976048'
  .applicationintroduction__flame
    .applicationintroduction__flame__block
      .applicationintroduction__flame__block__top
        スマホで かんたん
        %br/
        フリマアプリ
      .applicationintroduction__flame__block__middle
        メルカリはスマホカメラからすぐに出品できる
        %br/
        購入時も安心な独自システムのアプリです
      .applicationintroduction__flame__block__under
        = link_to image_tag("appstore.svg", width: '180'), "https://apps.apple.com/jp/app/id667861049?l=ja"
        = link_to image_tag("googleplay.svg", width: '180'), "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja" 
.categoryonintroduction
  %h2.categoryonintroduction__title
    人気のカテゴリー
  .categoryonintroduction__details
    %ul.categoryonintroduction__details__block
      %li.categoryonintroduction__details__block__listgoods
        レディース
      %li.categoryonintroduction__details__block__listgoods
        メンズ
      %li.categoryonintroduction__details__block__listgoods
        家電・スマホ・カメラ
      %li.categoryonintroduction__details__block__listgoods
        おもちゃ・ホビー・グッズ
.imagebody
  .imagebody__flame
    .imagebody__flame__block
      .imagebody__flame__block__sample
        .imagebody__flame__block__sample__text
          いろいろあります！
        .imagebody__flame__block__sample__details
          もっと見る！
    .imagebody__flame__itemslists
      = render partial: "items/detail", collection: @items, as: :item
            
.categoryonintroduction
  %h2.categoryonintroduction__title
    人気のブランド
  .categoryonintroduction__details
    %ul.categoryonintroduction__details__block
      %li.categoryonintroduction__details__block__listgoods
        シャネル
      %li.categoryonintroduction__details__block__listgoods
        ルイヴィトン
      %li.categoryonintroduction__details__block__listgoods
        シュプリーム
      %li.categoryonintroduction__details__block__listgoods
        ナイキ
.imagebody
  .imagebody__flame
    .imagebody__flame__block
      .imagebody__flame__block__sample
        .imagebody__flame__block__sample__text
          いろいろあります！
        .imagebody__flame__block__sample__details
          もっと見る！
    .imagebody__flame__itemslists
      = render partial: "items/detail", collection: @items, as: :item  
%aside
  .aside__flame
    .aside__flame__left-block
      .aside__flame__left-block__upper-row
        スマホでかんたんフリマアプリ
      .aside__flame__left-block__middle-row
        今すぐ無料ダウンロード！
      .aside__flame__left-block__under-row
        = link_to image_tag("fmarket_logo_red.svg", width: '130'), ""
    .aside__flame__right-block
      = image_tag("メルカリ（スマホ画像）.png", width: '290')
= render partial: "layouts/footer"

app/views/items/new.html.haml
= render "form", item: @item, categorys: @categorys, middle_categorys: nil, small_categorys: nil, prefectures: @prefectures

app/views/items/show.html.haml
= render partial: "layouts/header"

.item-show-wrapper
  .item-show-container
    .item-show-container__item
      .item-show-container__item__head
        %p #{@item.name}
      .item-show-container__item__info
        .item-show-container__item__info__images
          .item-show-container__item__info__images__large
            = image_tag @item.item_images[0].image.url
          .item-show-container__item__info__images__thumbnails
            - @item.item_images.each do |item_image|
              .item-show-container__item__info__images__thumbnails__thumbnail
                = image_tag item_image.image.url
        %table.item-show-container__item__info__table
          %tr
            %th 出品者
            %td
              .item-show-container__item__info__table__seller-name
                = link_to @item.seller.nickname, "#"
              .item-show-container__item__info__table__seller-evaluation
          %tr
            %th カテゴリー
            %td
              = link_to @item.category.parent.parent.name, "#"
              = link_to "> #{@item.category.parent.name}", "#"
              = link_to "> #{@item.category.name}", "#"
          %tr
            %th ブランド
            %td
              = link_to @item.brand, "#"
          %tr
            %th 商品のサイズ
            %td #{@item.size}
          %tr
            %th 商品の状態
            %td #{@item.condition}
          %tr
            %th 配送料の負担
            %td #{@item.charge}
          %tr
            %th 配送の方法
            %td #{@item.delivery}
          %tr
            %th 配送元地域
            %td
              = link_to @item.location, "#"
          %tr
            %th 発送日の目安
            %td #{@item.arrival_date}
      .item-show-container__item__price
        %span.item-show-container__item__price__price> ¥#{@item.price}
        %span.item-show-container__item__price__tax> （税込）
        %span.item-show-container__item__price__charge> 送料込み
      - unless current_user_is_seller?(@item)
        - if @item.status == "出品中"
          .item-show-container__item__buy.block-btn.block-btn-red
            = link_to "購入画面に進む", buy_item_path(@item)
        - elsif @item.status == "公開停止中"
          .item-show-container__item__buy.block-btn.block-btn-gray
            = link_to "公開停止中", "#"
        - else
          .item-show-container__item__buy.block-btn.block-btn-gray
            = link_to "売り切れました", "#"
      .item-show-container__item__comment
        = simple_format(@item.comment)
      - unless current_user_is_seller?(@item)
        .item-show-container__item__button
          .item-show-container__item__button__left
            .item-show-container__item__button__left__icon-btn
              %i.far.fa-heart
              %span.item-show-container__item__button__left__icon-btn__span> いいね!
              %span.item-show-container__item__button__left__icon-btn__span> 5
              = link_to "", "#", class: "item-show-container__item__button__left__icon-btn__link"
            .item-show-container__item__button__left__icon-btn
              %i.far.fa-flag
              %span.item-show-container__item__button__left__icon-btn__span> 不適切な商品の報告
              = link_to "", "#", class: "item-show-container__item__button__left__icon-btn__link"
          .item-show-container__item__button__right
            .item-show-container__item__button__right__icon-btn
              %i.fas.fa-unlock-alt
              %span.item-show-container__item__button__right__icon-btn__span> あんしん・あんぜんへの取り組み
              = link_to "", "#", class: "item-show-container__item__button__right__icon-btn__link"
  - if current_user_is_seller?(@item)
    .item-show-container
      .item-show-container__myitem
        .item-show-container__myitem__edit.block-btn.block-btn-red
          = link_to "商品の編集", edit_item_path(@item)
        - if @item.status == "出品中"
          .item-show-container__myitem__stop.block-btn.block-btn-gray
            =link_to "出品を一旦停止する", update_status_item_path(@item), method: :post
        - if @item.status == "公開停止中"
          .item-show-container__myitem__start.block-btn.block-btn-red
            =link_to "出品を再開する", update_status_item_path(@item), method: :post
        .item-show-container__myitem__or
          or
        .item-show-container__myitem__delete.block-btn.block-btn-gray
          =link_to "この商品を削除する", item_path(@item), method: :delete
  - if user_signed_in?
    .item-show-container
      .item-show-container__comment
        .item-show-container__comment__comments
        .item-show-container__comment__notice
          相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea{rows: 3, class: "item-show-container__comment__text"}
        .item-show-container__comment__submit.block-btn.block-btn-gray
          = link_to "コメントする", "#"
  .item-show-link
    .item-show-link__left
      = link_to "< 前の商品", "#"
    .item-show-link__right
      = link_to "次の商品 >", "#"
  .item-show-container
    .item-show-container__media
      .item-show-container__media__icons
        = link_to "#" do
          %i.fab.fa-facebook-square.fa-3x.icon-facebook.item-show-container__media__icons__icon
        = link_to "#" do
          %i.fab.fa-twitter-square.fa-3x.icon-twitter.item-show-container__media__icons__icon
        = link_to "#" do
          %i.fab.fa-line.fa-3x.icon-line.item-show-container__media__icons__icon
  .item-show-items-container
    .item-show-items-container__head
      = link_to "#{@item.seller.nickname}さんのその他の出品", "#"
    .item-show-items-container__items
      - if @seller_items.length != 0
        - @seller_items.each do |seller_item|
          .item-show-items-container__items__item
            = link_to "", item_path(seller_item)
            .item-show-items-container__items__item__image
              = image_tag seller_item.item_images[0].image.url
            .item-show-items-container__items__item__info
              .item-show-items-container__items__item__info__name
                #{seller_item.name}
              .item-show-items-container__items__item__info__price
                ¥#{seller_item.price}
  .item-show-items-container
    .item-show-items-container__head
      = link_to "#{@item.category.name} その他の商品", "#"
    .item-show-items-container__items
      - if @category_items.length != 0
        - @category_items.each do |category_item|
          .item-show-items-container__items__item
            = link_to "", item_path(category_item)
            .item-show-items-container__items__item__image
              = image_tag category_item.item_images[0].image.url
            .item-show-items-container__items__item__info
              .item-show-items-container__items__item__info__name
                #{category_item.name}
              .item-show-items-container__items__item__info__price
                ¥#{category_item.price}