config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, skip: :all

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'destroy', to: 'devise/sessions#destroy'
  end

  resources :signup ,only: [:index,:create] do
    collection do
      get 'registration'                               
      post 'registration',  to: 'signup#profile_validation' 
      get 'sms_authentication' 
      post 'sms_authentication',  to: 'signup#sms_post'
      get 'sms_confirmation'
      post 'sms_confirmation', to: 'signup#sms_check' 
      get 'address' 
      post 'address', to: 'signup#address_validation' 
      get 'card' 
      get 'done' 
    end
  end  


  resources :users do 
    collection do
      get 'logout'
      get 'profile'
      get 'certification'
      get 'card_registration'
      get 'card_information'
      get 'mypage'
    end
  end

  get 'users/identification(/:id)', to: 'users#identification', as: :user_identification
  resources :items do
    collection do
      get 'category'
    end
    member do
      post 'update_status'
      delete 'destroy_image'
      get 'buy'
      post 'pay'
    end
  end

  get 'items/confirm(/:id)', to: 'items#confirm', as: :items_confirm
  resources :cards


  resources :brands, only: [:index]
  resources :categorys, only: [:index]
end 

  

app/views/layouts/_footer.html.haml
%footer.footersetting
  .footersetting__flame
    .footersetting__flame__style-heading
      .footersetting__flame__style-heading__upperleft-block
        %h2
          メルカリについて
        %ul.listspace
          = link_to "会社概要（運営会社）", "https://about.mercari.com/", class: "listspace"
        %ul.listspace
          = link_to "採用情報", "https://www.mercari.com/jp/jobs/", class: "listspace"
        %ul.listspace
          = link_to "プレスリリース", "https://about.mercari.com/press/news/", class: "listspace"
        %ul.listspace
          = link_to "公式ブログ", "https://jp-news.mercari.com/", class: "listspace"
        %ul.listspace
          = link_to "メルカリロゴ利用ガイドライン", "https://www.mercari.com/jp/logo-guidelines/", class: "listspace"
        %iconspace-rightslide.iconspace
          = link_to image_tag("Twitterのアイコン素材 2.svg", width: '24')
        .iconspace
          = link_to image_tag("Twitterのアイコン素材 2.svg", width: '24')
      .footersetting__flame__style-heading__upperright-block
        %h2
          ヘルプ＆ガイド
        %ul.listspace
          = link_to "メルカリガイド", "https://www.mercari.com/jp/help_center/", class: "listspace"
        %ul.listspace
          = link_to "らくらくメルカリ便", "https://www.mercari.com/jp/rakuraku-mercari/", class: "listspace"
        %ul.listspace
          = link_to "ゆうゆうメルカリ便", "https://www.mercari.com/jp/yuyu-mercari/", class: "listspace"
        %ul.listspace
          = link_to "大型メルカリ便", "https://www.mercari.com/jp/rakuraku-ogata/", class: "listspace"
        %ul.listspace
          = link_to "車体取引ガイド", "https://www.mercari.com/jp/guide/car/", class: "listspace"
        %ul.listspace
          = link_to "メルカリあんしん・あんぜん宣言！", "https://www.mercari.com/jp/safe/description/", class: "listspace"
        %ul.listspac
          = link_to "偽ブランド品撲滅への取り組み", "https://www.mercari.com/jp/authenticity/", class: "listspace"
        %ul.listspace
          = link_to "メルカリボックス", "https://www.mercari.com/jp/box/", class: "listspace"
      .footersetting__flame__style-heading__lower-block
        %h2
          プライバシーと利用規約
        .footersetting__flame__style-heading__lower-block__left-block   
          %ul.listspace
            = link_to "プライバシーポリシー", "https://www.mercari.com/jp/help_center/", class: "listspace"
          %ul.listspace
            = link_to "メルカリ利用規約", "https://www.mercari.com/jp/help_center/", class: "listspace"
          %ul.listspace
            = link_to "あんしんスマホサポート制度に関する利用特約", "https://www.mercari.com/jp/help_center/", class: "listspace"
          %ul.listspace
            = link_to "コンプライアンスポリシー", "https://www.mercari.com/jp/help_center/", class: "listspace"
        .footersetting__flame__style-heading__lower-block__right-block 
          %ul.listspace
            = link_to "個人データの安全管理に係る基本方針", "https://www.mercari.com/jp/help_center/", class: "listspace"
          %ul.listspace
            = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/help_center/", class: "listspace"
          %ul.listspace
            = link_to "あんしんスマホサポート制度に関する利用特約", "https://www.mercari.com/jp/help_center/", class: "listspace"
          %ul.listspace
            = link_to "法令順守と犯罪抑止のために", "https://www.mercari.com/jp/help_center/", class: "listspace"
      .footersetting__flame__style-heading__country
        %h2
          国
        .footersetting__flame__style-heading__lower-block__left-block   
          %ul.listspace
            = link_to "日本", "https://www.mercari.com/jp/help_center/", class: "listspace"
          %ul.listspace
            = link_to "United States", "https://www.mercari.com/jp/help_center/", class: "listspace"
    .footersetting__flame__logo
      = link_to image_tag("fmarket_logo_red.svg", width: '130'), "",class: "subject"
      © Mercari, Inc.
    .exhibitioncamera
      - if user_signed_in?  
        = link_to image_tag("出品カメラ.png", width: '150'), new_item_path
      - else  
        = link_to image_tag("出品カメラ.png", width: '150'),new_user_session_path

app/views/layouts/_header.html.haml
.header
  .header__flame
    .header__flame__upper
      .header__flame__upper__logo
        = link_to image_tag("fmarket_logo_red.svg", width: '130'), root_path
      .header__flame__upper__search
        = form_tag('/search', method: :get, class: 'search-form') do
          %input.header__flame__upper__search__form-textbox{name: "keyword", placeholder: "何かお探しですか？", type: "text", value: ""}
          %button.header__flame__upper__search__form-button{title: "検索", type: "submit"}
            = image_tag("虫眼鏡の無料アイコン8.svg", width: '16')
    .header__flame__lower
      %ul.header__flame__lower__left-block
        %lu.header__flame__lower__left-block__category  
          %iconconnfig.header__flame__lower__left-block__category__icon
            = link_to image_tag("bxs-spreadsheet.svg", width: '24')
          .header__flame__lower__left-block__category__text
            = link_to "カテゴリーから探す", categorys_path, class: "disablelinklinecolor"
        %lu.header__flame__lower__left-block__brand  
          %iconconnfig.header__flame__lower__left-block__brand__text
            = link_to image_tag("bxs-spreadsheet.svg", width: '24')
          .header__flame__lower__left-block__brand__text
            = link_to "ブランドから探す", brands_path, class: "disablelinklinecolor"

      - if user_signed_in?          
        %ul.header__flame__lower__right-block
          %lu.header__flame__lower__right-block__eachblock
            %iconconnfig.header__flame__lower__right-block__eachblock__category
              = link_to image_tag("bxs-spreadsheet.svg", width: '24')
            .header__flame__lower__right-block__eachblock__category
              = link_to "いいね！一覧", "", class: "disablelinklinecolor"
          %lu.header__flame__lower__right-block__eachblock
            %iconconnfig.header__flame__lower__right-block__eachblock__category
              = link_to image_tag("bxs-spreadsheet.svg", width: '24')
            .header__flame__lower__right-block__eachblock__category
              = link_to "お知らせ", "", class: "disablelinklinecolor"
          %lu.header__flame__lower__right-block__eachblock
            %iconconnfig.header__flame__lower__right-block__eachblock__category
              = link_to image_tag("bxs-spreadsheet.svg", width: '24')
            .header__flame__lower__right-block__eachblock__category
              = link_to "やることリスト", "", class: "disablelinklinecolor"
          %lu.header__flame__lower__right-block__eachblock
            %iconconnfig.header__flame__lower__right-block__eachblock__category
              = link_to image_tag("bxs-spreadsheet.svg", width: '24')
            .header__flame__lower__right-block__eachblock__category
              = link_to "マイページ", mypage_users_path, method: :get, class: "disablelinklinecolor" 
      - else      
        .header__flame__lower__right-block__eachblock__signup
          = link_to "新規会員登録", signup_index_path, class: "btn_signup"
        .header__flame__lower__right-block__eachblock__login
          = link_to "ログイン", new_user_session_path, method: :post, class: "btn_login"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample65d
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield